### ISSUE TITLE
npm run watch和npm run dist均报错，运行时浏览器显示Cannot GET /items 

### ISSUE THREAD

**Issue by windsome** [lvBingo/Angelcrunch-react#3]
```
ERROR in ./static/images/wapsite/cssimage/arrow-left.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./~/stylus-loader!./static/css/wapsite/base-css.styl 6:67867-67922 6:68361-68416

ERROR in ./static/images/wapsite/cssimage/slider-on.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./~/stylus-loader!./static/css/wapsite/base-css.styl 6:72946-73000

ERROR in ./static/images/wapsite/cssimage/download_ios.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./~/stylus-loader!./static/css/wapsite/base-css.styl 6:73647-73704

ERROR in ./static/images/wapsite/cssimage/download_android.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./~/stylus-loader!./static/css/wapsite/base-css.styl 6:73753-73814

ERROR in ./static/images/wapsite/cssimage/iconfont-arrowright-2.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./~/stylus-loader!./static/css/wapsite/base-css.styl 6:75738-75804

ERROR in ./static/images/wapsite/cssimage/981273981273.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./~/stylus-loader!./static/css/wapsite/base-css.styl 6:77049-77106

ERROR in ./static/images/wapsite/cssimage/18237192837.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./~/stylus-loader!./static/css/wapsite/base-css.styl 6:77551-77607 6:77871-77927

ERROR in ./static/images/wapsite/cssimage/k12398712398223.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./static/css/wapsite/investor/details.css 6:3058-3121

ERROR in ./static/images/wapsite/cssimage/213iouy123871239u9123.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./static/css/wapsite/investor/details.css 6:7019-7088

ERROR in ./static/images/wapsite/cssimage/iconfont-iconloading.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./~/css-loader!./static/css/wapsite/list/style.css 6:1788-1856

ERROR in ./static/images/wapsite/angelcrunchbrandlogoinloginpage.png
Module build failed: Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
 @ ./src/components/login.js 49:61-129
webpack: bundle is now VALID.
```

**Comment by windsome** [comment]
修改webpack.config.js，不使用image-webpack能绕过这个问题。
```
            /*{
                test: /.*\.(png|gif|svg)$/i,
                loaders: [
                  'file?hash=sha512&digest=hex&name=[hash].[ext]',
                  'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}'
                ]
            },*/
            {
              test: /.*\.(png|gif|svg)$/i,
              loader: 'url?limit=250'
            },
```
