### ISSUE TITLE
运行时候报错了

### ISSUE THREAD

**Issue by jiehwa** [lvBingo/Angelcrunch-react#4]
ERROR in ./src/module.js
Module build failed: ReferenceError: [BABEL] /Users/jiehwa/github/Angelcrunch-react/src/module.js: Unknown option: /Users/jiehwa/github/Angelcrunch-react/.babelrc.optional
    at Logger.error (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-loader/index.js:14:22)
    at /Users/jiehwa/github/Angelcrunch-react/node_modules/babel-loader/lib/fs-cache.js:140:16
    at ReadFileContext.callback (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-loader/lib/fs-cache.js:27:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)

ERROR in ./src/utils/titleHelper.js
Module build failed: ReferenceError: [BABEL] /Users/jiehwa/github/Angelcrunch-react/src/utils/titleHelper.js: Unknown option: /Users/jiehwa/github/Angelcrunch-react/.babelrc.optional
    at Logger.error (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-loader/index.js:14:22)
    at /Users/jiehwa/github/Angelcrunch-react/node_modules/babel-loader/lib/fs-cache.js:140:16
    at ReadFileContext.callback (/Users/jiehwa/github/Angelcrunch-react/node_modules/babel-loader/lib/fs-cache.js:27:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
 @ multi common

**Comment by Beatusvir** [comment]
I'm receiving this message as well.

**Comment by cuitianze** [comment]
I'm receiving this message as well.

**Comment by zbinlin** [comment]
这应该是升级到 `babel 6` 导致的，退回 babel 5.8 应该可以，或者按以下的方式修改：

1. 修改 `.babelrc` 文件，内容如下：
  ```json
  {
    "presets": ["es2015", "stage-0", "react"],
    "plugins": ["transform-decorators-legacy"]
  }
  ```
2. 安装 reset-es2015, babel-preset-stage-0, babel-preset-react, babel-plugin-transform-decorators-legacy：
  ```
  npm install babel-preset-react babel-preset-stage-0 babel-preset-react babel-plugin-transform-decorators-legacy
  ```
3. 修改 `src/components/notification.js` 里的第18行，在右括号后加上英文分号（;）

**注：**如果在 linux 下，需要将 `./src/components/` 下的 `Header.js` 改成小写：`header.js`

按上面的修改应该可以 build 了，但是 build 后打开页面发现由于有个需要外连的 API 无法取回数据而导致页面无法完成加载。
